before_script:
  - psql -c 'create database sqlalchemy_defaults_test;' -U postgres

language: python
python:
  - 2.6
  - 2.7
  - 3.3
install:
  - pip install -q -e . --use-mirrors
script:
  - python setup.py test
